name: floating_menu_overlay
description: A customizable floating menu overlay for Android. Supports 0-6 draggable menu icons, custom colors/gradients, shapes (circular/rect), sizes, borders, and app launcher as center icon. Clickable with Flutter callbacks.
version: 1.0.0
homepage: https://github.com/prakharAKGa/floating_menu_overlay
repository: https://github.com/prakharAKGa/floating_menu_overlay

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.floating_menu_overlay
        pluginClass: FloatingMenuOverlayPlugin